# Generated by Django 4.0 on 2021-12-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_datetime',
            new_name='due',
        ),
    ]
